
  CREATE OR REPLACE FORCE VIEW XX_CL_JOURNAL_VW
  AS 
  SELECT gjh.JE_HEADER_ID,
  GJB.name BatchName,
  GJH.name Journal_Name,
  GJB.DESCRIPTION BatchDescription,
  300000001380026 LedgerId,
  --GJL.JE_LINE_NUM line_num,
  gjh.period_name AccountingPeriodName,
  gjh.POSTED_DATE AccountingDate,
  gjh.JE_SOURCE UserSourceName,
  gjc.JE_CATEGORY_NAME UserCategoryName,
  'false' ErrorToSuspenseFlag,
  'false' SummaryFlag,
  'N' ImportDescriptiveFlexField,
  Reference4 header_name,
  Reference5 header_description,
  gjh.period_name PeriodName,
  '999' GroupId ,
  2001 ChartOfAccountsId ,
  gjh.ACTUAL_FLAG BalanceType,
  NULL CodeCombinationId,
  '11' Segment1,
  DECODE(ACCOUNTED_CR, NULL,'111171','130791') Segment2,
  '000' Segment3,
  '000' Segment4,
  '000' Segment5,
  '000' Segment6,
  '11' Segment7,
  '0000' Segment8,
  '000' Segment9,
  NULL Segment10 ,
  NULL Segment11 ,
  NULL Segment12 ,
  NULL Segment13 ,
  NULL Segment14 ,
  NULL Segment15 ,
  NULL Segment16 ,
  NULL Segment17 ,
  NULL Segment18 ,
  NULL Segment19 ,
  NULL Segment20 ,
  NULL Segment21 ,
  NULL Segment22 ,
  NULL Segment23 ,
  NULL Segment24 ,
  NULL Segment25 ,
  NULL Segment26 ,
  NULL Segment27 ,
  NULL Segment28 ,
  NULL Segment29 ,
  NULL Segment30 ,
  GJH.CURRENCY_CODE CurrencyCode,
  GJL.ACCOUNTED_CR EnteredCrAmount ,
  GJL.ACCOUNTED_DR EnteredDrAmount ,
  GJL.ACCOUNTED_CR AccountedCr ,
  GJL.ACCOUNTED_DR AccountedDr ,
  NULL StatisticalValue ,
  NULL UserCurrencyConversionType ,
  NULL CurrencyConversionDate ,
  NULL CurrencyConversionRate ,
  NULL CurrencyConversionType ,
  NULL Reference1,
  NULL Reference2,
  NULL Reference3,
  NULL Reference6,
  NULL Reference7,
  NULL Reference8,
  NULL Reference9,
  NULL Reference10,
  NULL Reference11,
  NULL Reference12,
  NULL Reference13,
  NULL Reference14,
  NULL Reference15,
  NULL Reference16,
  NULL Reference17,
  NULL Reference18,
  NULL Reference19,
  NULL Reference20,
  NULL Reference21,
  NULL Reference22,
  NULL Reference23,
  NULL Reference24,
  NULL Reference25,
  NULL Reference26,
  NULL Reference27,
  NULL Reference28,
  NULL Reference29,
  NULL Reference30,
  NULL ReferenceDate ,
  NULL Attribute1,
  NULL Attribute2,
  NULL Attribute3,
  NULL Attribute4,
  NULL Attribute5,
  NULL Attribute6,
  NULL Attribute7,
  NULL Attribute8,
  NULL Attribute9,
  NULL Attribute10,
  NULL Attribute11,
  NULL Attribute12,
  NULL Attribute13,
  NULL Attribute14,
  NULL Attribute15,
  NULL Attribute16,
  NULL Attribute17,
  NULL Attribute18,
  NULL Attribute19,
  NULL Attribute20,
  NULL AttributeCategory ,
  NULL AttributeCategory2 ,
  NULL AttributeCategory3 ,
  NULL AverageJournalFlag ,
  NULL BalancingSegmentValue ,
  NULL DescrFlexErrorMessage ,
  NULL GlSlLinkId ,
  NULL GlSlLinkTable ,
  NULL InvoiceAmount ,
  NULL InvoiceDate ,
  NULL InvoiceIdentifier ,
  gjc.JE_CATEGORY_NAME JeCategoryName ,
  gjh.JE_SOURCE JeSourceName ,
  NULL JgzzReconReference ,
  NULL ManagementSegmentValue ,
  NULL ObjectVersionNumber ,
  NULL OriginatingBalSegValue ,
  NULL SetOfBooksId ,
  'New' Status ,
  NULL TaxCode ,
  NULL TransactionDate ,
  NULL USSGLTransactionCode ,
  NULL GlInterfaceId ,
  NULL LegalEntityIdentifier ,
  NULL LedgerName
FROM apps.GL_JE_HEADERS GJH,
  apps.GL_JE_LINES GJL,
  apps.GL_JE_BATCHES GJB,
  apps.GL_JE_CATEGORIES gjc,
  apps.gl_ledgers gl,
  apps.gl_code_combinations_kfv gcc,
  xx_journal_staging stg
WHERE GJH.JE_HEADER_ID     =GJL.JE_HEADER_ID
AND GJB.JE_BATCH_ID        =GJH.JE_BATCH_ID
AND gcc.CODE_COMBINATION_ID=GJL.CODE_COMBINATION_ID
AND gjc.JE_CATEGORY_NAME   =GJH.JE_CATEGORY
AND gl.LEDGER_ID           = GJH.LEDGER_ID
AND gjh.JE_HEADER_ID       = stg.JE_HEADER_ID(+)
AND GJH.JE_SOURCE          = 'Cost Management'
AND stg.JE_HEADER_ID      IS NULL
  --AND GJB.NAME LIKE 'GLbatchName%'
  --and gjh.name like 'JUN-12 Inventory LKR 2';
AND gjh.POSTED_DATE > '01-MAR-18';
