create or replace procedure xxn4_add_shipping_lines
(
p_id VARCHAR2,
p_scac VARCHAR2 default null,
p_bic_code VARCHAR2 default null,
p_name VARCHAR2,
p_address_line_1 VARCHAR2 default null,
p_address_line_2 VARCHAR2 default null,
p_address_line_3 VARCHAR2 default null,
p_city VARCHAR2 default null,
p_state VARCHAR2 default null,
p_country_id VARCHAR2 default null,
p_mail_code VARCHAR2 default null,
p_tel VARCHAR2 default null,
p_fax VARCHAR2 default null,
p_contact VARCHAR2 default null,
p_title VARCHAR2 default null,
p_active VARCHAR2 default null,
p_active_on_sparcs VARCHAR2 default null,
p_notes VARCHAR2 default null,
p_created DATE default null,
p_creator VARCHAR2 default null,
p_changed DATE default null,
p_changer VARCHAR2 default null,
p_debtor_nbr NUMBER default null,
p_payment_nbr NUMBER default null,
p_payment_cycle VARCHAR2 default null,
p_account_type VARCHAR2 default null,
p_account_status VARCHAR2 default null,
p_national_id VARCHAR2 default null,
p_account_code VARCHAR2 default null,
p_tax_id VARCHAR2 default null,
p_freepool_allowance NUMBER default null,
p_tax_id_type VARCHAR2 default null,
p_tax_class VARCHAR2 default null,
p_line_pdiem_dry_ffdays NUMBER default null,
p_line_pdiem_reefer_ffdays NUMBER default null,
p_line_pdiem_dry_lfdays NUMBER default null,
p_line_pdiem_reefer_lfdays NUMBER default null,
p_crnc_id VARCHAR2 default null,
p_agent_id VARCHAR2 default null,
p_business_id1 VARCHAR2 default null,
p_business_id2 VARCHAR2 default null,
p_long_name VARCHAR2 default null,
p_email_address VARCHAR2 default null,
p_mty_return_loc_id VARCHAR2 default null,
p_user_group_id VARCHAR2 default null,
p_export_freepool NUMBER default null,
p_other_name VARCHAR2 default null,
p_other_address_line_1 VARCHAR2 default null,
p_other_address_line_2 VARCHAR2 default null,
p_other_address_line_3 VARCHAR2 default null,
p_other_city VARCHAR2 default null,
p_other_state VARCHAR2 default null,
p_other_country_id VARCHAR2 default null,
p_other_mail_code VARCHAR2 default null,
p_operation VARCHAR2,
p_status out VARCHAR2,
p_error out varchar2 
)
as
begin

  if p_operation is null or p_operation not in ('I','U')
  then
    p_status := 'E';
    p_error := 'Invalid value for p_operation (Valid values: I,U)';
    return;
  end if;
 
 begin
 insert into xxn4_shipping_lines
 (id,
scac,
bic_code,
name,
address_line_1,
address_line_2,
address_line_3,
city,
state,
country_id,
mail_code,
tel,
fax,
contact,
title,
active,
active_on_sparcs,
notes,
created,
creator,
changed,
changer,
debtor_nbr,
payment_nbr,
payment_cycle,
account_type,
account_status,
national_id,
account_code,
tax_id,
freepool_allowance,
tax_id_type,
tax_class,
line_pdiem_dry_ffdays,
line_pdiem_reefer_ffdays,
line_pdiem_dry_lfdays,
line_pdiem_reefer_lfdays,
crnc_id,
agent_id,
business_id1,
business_id2,
long_name,
email_address,
mty_return_loc_id,
user_group_id,
export_freepool,
other_name,
other_address_line_1,
other_address_line_2,
other_address_line_3,
other_city,
other_state,
other_country_id,
other_mail_code,
cl_operation
)
 select p_id,
p_scac,
p_bic_code,
p_name,
p_address_line_1,
p_address_line_2,
p_address_line_3,
p_city,
p_state,
p_country_id,
p_mail_code,
p_tel,
p_fax,
p_contact,
p_title,
p_active,
p_active_on_sparcs,
p_notes,
p_created,
p_creator,
p_changed,
p_changer,
p_debtor_nbr,
p_payment_nbr,
p_payment_cycle,
p_account_type,
p_account_status,
p_national_id,
p_account_code,
p_tax_id,
p_freepool_allowance,
p_tax_id_type,
p_tax_class,
p_line_pdiem_dry_ffdays,
p_line_pdiem_reefer_ffdays,
p_line_pdiem_dry_lfdays,
p_line_pdiem_reefer_lfdays,
p_crnc_id,
p_agent_id,
p_business_id1,
p_business_id2,
p_long_name,
p_email_address,
p_mty_return_loc_id,
p_user_group_id,
p_export_freepool,
p_other_name,
p_other_address_line_1,
p_other_address_line_2,
p_other_address_line_3,
p_other_city,
p_other_state,
p_other_country_id,
p_other_mail_code,
p_operation
from dual;

--commit;
 p_status := 'S';
 p_error := 'Success';
exception
when others then
 p_status := 'E';
 p_error := sqlerrm;
end;
 

end;
